version: '3'
services:
  backend:
    depends_on:
      - mongodb
    restart: always
    build: .
    ports:
      - '8080:3000'
    environment:
      - DB_URL=mongodb://db_mongo
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  database:
    image: mongo
    volumes:
      - mongodata:/data/db
    ports:
      - '27017:27017'

volumes:
  mongodata:
